// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcBeamParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CalcBeamParams'](arg1, arg2, arg3, arg4);
}

export function CalcEnergyRecommendation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CalcEnergyRecommendation'](arg1, arg2, arg3, arg4);
}

export function ComputeFaceHeatmap(arg1, arg2) {
  return window['go']['main']['App']['ComputeFaceHeatmap'](arg1, arg2);
}

export function EvaluateOrientation(arg1, arg2) {
  return window['go']['main']['App']['EvaluateOrientation'](arg1, arg2);
}

export function GetDefaultScannerConfig() {
  return window['go']['main']['App']['GetDefaultScannerConfig']();
}

export function GetFilters() {
  return window['go']['main']['App']['GetFilters']();
}

export function GetMaterials() {
  return window['go']['main']['App']['GetMaterials']();
}

export function GetMeshInfo() {
  return window['go']['main']['App']['GetMeshInfo']();
}

export function GetScannerPresets() {
  return window['go']['main']['App']['GetScannerPresets']();
}

export function GetVertexBuffer() {
  return window['go']['main']['App']['GetVertexBuffer']();
}

export function LoadMeshFromBytes(arg1, arg2) {
  return window['go']['main']['App']['LoadMeshFromBytes'](arg1, arg2);
}

export function PickAndLoadMesh() {
  return window['go']['main']['App']['PickAndLoadMesh']();
}

export function RunOptimization(arg1) {
  return window['go']['main']['App']['RunOptimization'](arg1);
}
