// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {raycaster} from '../models';
import {app} from '../models';
import {main} from '../models';

export function CalcBeamParams(arg1:number,arg2:number,arg3:string,arg4:string):Promise<string>;

export function CalcEnergyRecommendation(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function ComputeFaceHeatmap(arg1:number,arg2:number):Promise<string>;

export function EvaluateOrientation(arg1:number,arg2:number):Promise<string>;

export function GetDefaultScannerConfig():Promise<raycaster.ScannerConfig>;

export function GetFilters():Promise<string>;

export function GetMaterials():Promise<string>;

export function GetMeshInfo():Promise<app.MeshInfo>;

export function GetScannerPresets():Promise<string>;

export function GetVertexBuffer():Promise<Array<number>>;

export function LoadMeshFromBytes(arg1:string,arg2:Array<number>):Promise<app.MeshInfo>;

export function PickAndLoadMesh():Promise<app.MeshInfo>;

export function RunOptimization(arg1:main.runRequest):Promise<string>;
